version: '3.7'
services:
  server:
    build: .
    env_file:
      - ${HOTLINE_ENV?env is not set}.env
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - ${SERVER_PORT}:8000
    depends_on:
      - db
  db:
    env_file:
      - ${HOTLINE_ENV?env is not set}.env
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbit_mq:
    env_file:
      - ${HOTLINE_ENV?env is not set}.env
    image: rabbitmq
    ports:
      - 5672:5672

  worker:
    build: .
    env_file:
      - ${HOTLINE_ENV?env is not set}.env
    command: celery -A hotline worker -l info
    volumes:
      - .:/code
    depends_on:
      - rabbit_mq

volumes:
  postgres_data: