version: '3.7'
services:
  server:
    build: .
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - ${SERVER_PORT}:8000
    depends_on:
      - db
  db:
    environment:
      - POSTGRES_UESRNAME=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  rabbit_mq:
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=myvhost
    image: rabbitmq
    ports:
      - 5672:5672
  worker:
    build: .
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
    command: celery -A hotline worker -l info
    volumes:
      - .:/code
    depends_on:
      - rabbit_mq
volumes:
  postgres_data: