# Generated by Django 3.0.7 on 2020-06-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200621_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotlineuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='hotlineuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='hotlineuser',
            name='last_name',
        ),
    ]
