# Generated by Django 3.0.7 on 2020-06-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200622_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='level_config',
            field=models.TextField(default='', max_length=1024),
        ),
    ]
