# Generated by Django 3.0.7 on 2020-06-27 19:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_level_level_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='', max_length=1024),
        ),
    ]
